version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  objectives:
    build: .
    command: gunicorn config.wsgi -b 0.0.0.0:8000
    command: python /code/manage.py runserver 0.0.0.0:8000
    environment:
      - DJANGO_SECRET_KEY=sadkasn!n9123LDSAadascjndsdsadnbaslkd
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
